/*TYPE EINFO IS RECORD ( EID EMPLOYEES.EMPLOYEE_ID%TYPE,
                       LNA EMPLOYEES.LAST_NAME%TYPE,
                       SAL EMPLOYEES.SALARY%TYPE                   
                      );
TYPE ELIST IS TABLE OF EINFO;*/
                      
CREATE TABLE EMP_SAL AS SELECT E.EMPLOYEE_ID,E.SALARY FROM EMPLOYEES E WHERE 1 =2 ;


--  FORALL

DECLARE
EL test_utility.ELIST;
ER TEST_UTILITY.EINFO;
BEGIN
  SELECT E.EMPLOYEE_ID,E.LAST_NAME,E.SALARY BULK COLLECT INTO EL FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = 80;
  FORALL I IN EL.FIRST .. EL.LAST
   INSERT INTO EMP_SAL(EMPLOYEE_ID, SALARY) VALUES (EL(I).EID, EL(I).SAL);   

END;
/

SELECT * FROM EMP_SAL; 
select * from employees e where e.employee_id = 216

-- ATTRIBUTES: BULKEXCEPTION AND BULKCOUNT

-- WHERE ARE THE EXCEPTIONS??? 
DECLARE
TYPE MAILS IS TABLE OF EMPLOYEES.EMAIL%TYPE;
ML MAILS := MAILS('123@TEST.COM','123@TEST.COM','456@TEST.COM','789@TEST.COM','456@TEST.COM');
N NUMBER(2) := 1; 
BEGIN
  FORALL I IN ML.FIRST .. ML.LAST
  SAVE EXCEPTIONS
    INSERT INTO EMPLOYEES SELECT EMPLOYEES_SEQ.NEXTVAL,
                          FIRST_NAME,
                          LAST_NAME,
                          ML(I),
                          PHONE_NUMBER,
                          HIRE_DATE,
                          JOB_ID,
                          SALARY,
                          COMMISSION_PCT,
                          MANAGER_ID,
                          DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 888;
   
  FOR I IN 1.. SQL%BULK_EXCEPTIONS.COUNT LOOP
    DBMS_OUTPUT.put_line(SQL%BULK_EXCEPTIONS(I).ERROR_INDEX ||' '||SQL%BULK_EXCEPTIONS(I).ERROR_CODE);   
  END LOOP;   
END; 
/


-- BULK COLLECT INTO (SELECT&FETCH)
DECLARE
CURSOR C1(PID NUMBER) IS SELECT E.EMPLOYEE_ID, E.LAST_NAME, E.SALARY FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = PID; 
TYPE C2 IS REF CURSOR RETURN TEST_UTILITY.EINFO;
C C2; 
TYPE EINFO IS RECORD ( EID EMPLOYEES.EMPLOYEE_ID%TYPE,
                       LNA EMPLOYEES.LAST_NAME%TYPE,
                       SAL EMPLOYEES.SALARY%TYPE                   
                      );
TYPE ELIST IS TABLE OF EINFO;

ELL ELIST;
EL2 ELIST;

BEGIN
  OPEN C FOR SELECT E.EMPLOYEE_ID, E.LAST_NAME, E.SALARY FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = 100;
  -- FETCH REF CURSOR
  FETCH C BULK COLLECT INTO ELL; 
  
  FOR I IN ELL.FIRST..ELL.LAST LOOP
    DBMS_OUTPUT.put_line(ELL(I).EID||' '||ELL(I).LNA);
  END LOOP;
  CLOSE C;
  DBMS_OUTPUT.put_line('---------------------------------');
  -- FETCH CURSOR
   
  OPEN C1(50);  
  FETCH C1 BULK COLLECT INTO EL2;  
   
  FOR I IN EL2.FIRST..EL2.LAST LOOP
    DBMS_OUTPUT.put_line(EL2(I).EID||' '||EL2(I).LNA);
  END LOOP;
  
  
  CLOSE C1;  

END;
/ 



-- RETURNING BULK COLLECT INTO

DECLARE
TYPE EINFO IS RECORD ( EID EMPLOYEES.EMPLOYEE_ID%TYPE,
                       LNA EMPLOYEES.LAST_NAME%TYPE,
                       SAL EMPLOYEES.SALARY%TYPE                   
                      );
TYPE ELIST IS TABLE OF EINFO;
RECV_LIST ELIST;
BEGIN
  UPDATE EMPLOYEES E SET E.SALARY = E.SALARY+100 WHERE E.DEPARTMENT_ID = 80
  RETURNING E.EMPLOYEE_ID,E.LAST_NAME,E.SALARY BULK COLLECT INTO RECV_LIST;
  
  FOR I IN RECV_LIST.FIRST .. RECV_LIST.LAST LOOP
    DBMS_OUTPUT.put_line('UPD '||RECV_LIST(I).LNA ||' '||RECV_LIST(I).SAL);
  
  END LOOP;
  
  DELETE FROM EMPLOYEES E WHERE E.EMPLOYEE_ID > 210 
  RETURNING  E.EMPLOYEE_ID,E.LAST_NAME,E.SALARY BULK COLLECT INTO RECV_LIST;
  
  FOR I IN RECV_LIST.FIRST .. RECV_LIST.LAST LOOP
    DBMS_OUTPUT.put_line('DEL '||RECV_LIST(I).LNA ||' '||RECV_LIST(I).SAL);
  
  END LOOP;
  

END; 
/


-- RETURNING BULK COLLECT INTO WITH FOR ALL

DECLARE
TYPE EINFO IS RECORD ( EID EMPLOYEES.EMPLOYEE_ID%TYPE,
                       LNA EMPLOYEES.LAST_NAME%TYPE,
                       SAL EMPLOYEES.SALARY%TYPE                   
                      );
TYPE ELIST IS TABLE OF EINFO;
RETURN_LIST ELIST;
UPD_LIST ELIST;
BEGIN
  SELECT EMPLOYEE_ID, LAST_NAME, SALARY*1.2 BULK COLLECT INTO UPD_LIST FROM EMPLOYEES WHERE DEPARTMENT_id = 100;
  FORALL I IN UPD_LIST.FIRST ..UPD_LIST.LAST 
    UPDATE EMPLOYEES E SET E.SALARY =UPD_LIST(I).SAL WHERE E.DEPARTMENT_ID = 100 AND E.EMPLOYEE_ID = UPD_LIST(I).EID
    RETURNING E.EMPLOYEE_ID,E.LAST_NAME,E.SALARY BULK COLLECT INTO RETURN_LIST;  
    
    FOR I IN UPD_LIST.FIRST .. UPD_LIST.LAST LOOP
    DBMS_OUTPUT.put_line('UPD_LIST '||UPD_LIST(I).LNA ||' '||UPD_LIST(I).SAL);
    END LOOP;

    FOR I IN RETURN_LIST.FIRST .. RETURN_LIST.LAST LOOP
    DBMS_OUTPUT.put_line('RETURN_LIST '||RETURN_LIST(I).LNA ||' '||RETURN_LIST(I).SAL||' '||SQL%BULK_ROWCOUNT(I));
    END LOOP; 

    ROLLBACK; 
END; 
/

SELECT * FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = 100;
SELECT * FROM EMP2  
-- ASSOCIATE ARRAY BULK BIND (????)

CREATE TABLE EMPS2 AS SELECT * FROM EMPLOYEES WHERE 1 =2; 
DECLARE
TYPE EMP_LIST IS TABLE OF EMPLOYEES%ROWTYPE;

EPL EMP_LIST;
BEGIN
  SELECT * BULK COLLECT INTO EPL FROM EMPLOYEES E WHERE E.DEPARTMENT_ID = 100; 
  FORALL I IN EPL.FIRST .. EPL.LAST 
  INSERT INTO EMPS2 VALUES EPL(I);
  
END; 

SELECT * FROM EMPS2 
